services:
  - type: web
    name: miconnect
    env: php
    plan: free
    region: oregon
    buildCommand: |
      composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-progress
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    healthCheckPath: /
